### ISSUE TITLE
[FEATURE] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by sena-22** [sena-22/pre-onboarding-10th-3-9#1]
### 🤸 Describe the required feature
typescript, prettier, eslint, husky 설치 및 설정

### 🏊 Todo

- [x] typescript, prettier, eslint, husky 설치
- [x] prettier, eslint, tsconfig 파일 추가
- [x] husky 세팅
- [x] issue, PR 템플릿 추가
- [x] type 적용
